export default Object.freeze({
  GETSTARTED: 'Welcome',
  HOME: 'Home',
  FAVOUROTE: 'Favorites',
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGETPASSWORD: 'Forgetpassword',
  RESET: 'Reset',
  CODEENTER: 'Code',
  TAKEIMAGE: 'TakeImage',
  USERATTRIBUTES: 'UserAttributes',
  USERHEIGHTANDWEIGHT: 'UserHeightAndWeight',
  HEIGHT: 'Height',
});
