import {StyleSheet} from 'react-native';
import colors from '../../../config/colors';
import {
  FONT_BOLD,
  FONT_SEMIBOLD,
  FONT_Regular,
  FONT_LIGHT,
  FONT_MEDIUM,
} from '../../../config/Constant';

const styles = StyleSheet.create({
  conatiner: {flex: 1, backgroundColor: colors.white},
  edit: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.COLOR_FILLED,
    width: 60,
    height: 20,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  emailText: {
    fontFamily: FONT_Regular,
    fontSize: 12,
    color: colors.COLOR_BORDER,
  },
  editText: {
    fontFamily: FONT_Regular,
    fontSize: 12,
    color: colors.COLOR_FILLED,
  },
  image: {
    width: 60,
    height: 60,
    overflow: 'hidden',
    borderRadius: 30,
    backgroundColor: colors.white,
  },
  name: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 18,
    color: colors.black,
  },
  hiarContainer: {
    borderRadius: 20,
    borderColor: colors.bitblue,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOpacity: 0.1,
    elevation: 2,
    shadowRadius: 10,
    shadowOffset: {width: 1, height: 50},
    height: 82,
    width: 88,
    marginLeft: 15,
    alignSelf: 'center',
    marginBottom: 5,
    marginTop: 10,
  },
  acceseries: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 12,
    marginHorizontal: 20,
    marginBottom: 5,
    marginTop: 10,
    color: colors.black,
  },
  regularText: {fontFamily: FONT_Regular, fontSize: 12, color: colors.black},
  glassesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginBottom: 5,
    marginTop: 10,
  },
  semiText: {fontFamily: FONT_SEMIBOLD, fontSize: 12, color: colors.black},
  mediumText: {fontFamily: FONT_MEDIUM, fontSize: 12, color: colors.black},
  genderView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginBottom: 10,
    marginTop: 5,
    flex: 1,
  },
  view: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 30,
    marginBottom: 5,
  },
  recommendedColor: {
    marginHorizontal: 20,
    fontSize: 14,
    marginTop: 5,
    fontFamily: FONT_SEMIBOLD,
    color: colors.black,
  },
  colorName: {
    fontFamily: FONT_Regular,
    fontSize: 10,
    textAlign: 'center',
    padding: 20,
    color: colors.black,
  },
});
export default styles;
